# Generated by Django 5.2 on 2026-01-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('twint', 'Twint'), ('card', 'Card'), ('paypal', 'Paypal'), ('crypto', 'Crypto')], max_length=20),
        ),
    ]
