# syntax=docker/dockerfile:1

# 1. Minimal Python interpreter
FROM python:3.12-slim

# 2. Workdir inside of container
WORKDIR /app

# 3. Install system dependencies (only needed for assembly Python-packages e.g. psycopg2, Pillow, etc.)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        libpq-dev \
        gcc \
    && rm -rf /var/lib/apt/lists/*

# apt-get update – обновляет списки пакетов
# apt-get install – ставит системные зависимости
# build-essential – нужен для сборки C-расширений Python-пакетов
# gcc – компилятор C, нужен для тех же пакетов
# libpq-dev – dev-заголовки PostgreSQL (требуются для psycopg2)
# --no-install-recommends – не ставить лишний мусор, экономия места
# rm -rf /var/lib/apt/lists/* – очищаем кеш apt (это экономит 100–300 МБ)


# 4. Copy requirements.txt only (for better cache usage)
COPY requirements-dev.txt .


# 5. Install Python-dependencies
RUN pip install --upgrade pip && \
    pip install -r requirements-dev.txt

# 6. Copy entire project (excluding files in .dockerignore)
COPY . .

# 7. Disable writing .pyc files and buffering stdout(standard output)/stderr(standard error)
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 8. Expose port (merely nominal for documentation)
EXPOSE 8000

# 9. Default command - will be overridden by compose
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
