# Generated by Django 5.2 on 2025-05-12 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_status_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_deleted',
        ),
    ]
