# Generated by Django 5.2 on 2025-05-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_payment_amount_alter_payment_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='order',
            name='price_diff',
            field=models.BooleanField(default=False),
        ),
    ]
