# Generated by Django 5.2 on 2025-06-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_payment_deleted_at_remove_payment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('twint', 'Twint'), ('paypal', 'Paypal'), ('crypto', 'Crypto')], max_length=20),
        ),
    ]
