# Generated by Django 5.2 on 2025-06-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
