# Generated by Django 5.2 on 2025-07-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_payment_amount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shop',
            name='unique_owner_shop_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
