# Generated by Django 5.2 on 2025-07-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userloginhistory_user'),
        ('core', '0014_remove_shop_unique_owner_shop_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_shop_product_name',
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_shop_name'),
        ),
    ]
