# Generated by Django 5.2 on 2025-07-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_product_unique_shop_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='is_deleted',
        ),
    ]
