# Generated by Django 5.2 on 2025-07-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_category_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_apartment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(default='N/A', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(default='N/A', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_first_name',
            field=models.CharField(default='N/A', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_house_number',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_last_name',
            field=models.CharField(default='N/A', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_street',
            field=models.CharField(default='N/A', max_length=128),
            preserve_default=False,
        ),
    ]
