# Generated by Django 5.2 on 2025-07-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_order_shipping_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_additional_info',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
