# Generated by Django 5.2 on 2025-07-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_category_unique_category_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
