# Generated by Django 5.2 on 2025-07-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_category_unique_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='shop',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='category'),
        ),
    ]
