# Generated by Django 5.2 on 2025-08-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_category_shop_alter_category_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shop',
            name='unique_owner_shop_name',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='slug',
        ),
    ]
