# Generated by Django 5.2 on 2025-08-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_price_orderitem_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_price',
            new_name='product_total_price',
        ),
    ]
