# Generated by Django 5.2 on 2025-08-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_order_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
