# Generated by Django 5.2 on 2025-08-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_order_shipping_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_email',
        ),
    ]
