# Generated by Django 5.2 on 2025-08-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_order_shipping_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_info',
            field=models.CharField(blank=True, null=True),
        ),
    ]
