# Generated by Django 5.2 on 2025-08-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_order_delivered_at_order_shipping_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_info',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
