# Generated by Django 5.2 on 2025-08-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_order_tracking_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_info',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
