# Generated by Django 5.2 on 2025-09-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_productimage_alt_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position', 'created_at']},
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='order',
            new_name='position',
        ),
    ]
