# Generated by Django 5.2 on 2025-10-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position']},
        ),
    ]
