# Generated by Django 5.2 on 2025-10-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_shippinginfo_additional_info_and_more'),
        ('core', '0042_alter_product_category_alter_product_shop'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='unique_pending_order_per_user'),
        ),
    ]
