# Generated by Django 5.2 on 2025-12-31 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price_diff',
        ),
    ]
