# Generated by Django 5.2 on 2026-01-05 04:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_order_price_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
