# Generated by Django 5.2 on 2026-01-10 11:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_order_delivery_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=Decimal('8.50'), max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_id_snapshot',
        ),
        migrations.AddField(
            model_name='order',
            name='items_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_pk_snapshot',
            field=models.PositiveIntegerField(default=666),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shop'),
        ),
    ]
