# Generated by Django 5.2 on 2026-01-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_deliverysettings_remove_order_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
