# Generated by Django 5.2 on 2026-01-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
