# Generated by Django 5.2 on 2026-01-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_product_shop_delete_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_image_url',
            field=models.URLField(blank=True),
        ),
    ]
