# Generated by Django 5.2 on 2026-01-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_orderitem_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='primary_image_url',
            field=models.URLField(blank=True),
        ),
    ]
