# Generated by Django 5.2 on 2026-01-20 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_userprofile_role_delete_sellerprofile'),
        ('core', '0052_product_primary_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.customerprofile'),
        ),
    ]
