# Generated by Django 5.2 on 2025-05-07 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_email_verification_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_verification_code',
            new_name='email_verification_token',
        ),
    ]
