# Generated by Django 5.2 on 2025-05-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
