# Generated by Django 5.2 on 2025-07-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_shippinginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='additional_info',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
