# Generated by Django 5.2 on 2025-08-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_shippinginfo_city_alter_shippinginfo_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
