# Generated by Django 5.2 on 2025-08-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_shippinginfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginhistory',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
