# Generated by Django 5.2 on 2025-09-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userloginhistory_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='additional_info',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='apartment',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='city',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='country',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='first_name',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='house_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='last_name',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='phone',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='postal_code',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='street',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='userloginhistory',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller'), ('admin', 'Admin')], default='customer', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
