# Generated by Django 5.2 on 2025-12-22 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_deleted',
        ),
    ]
