# Generated by Django 5.2 on 2025-12-23 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_customerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_verification_token',
            new_name='verification_token',
        ),
    ]
