# Generated by Django 5.2 on 2026-01-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('manager', 'Manager'), ('customer', 'Customer')], default='customer', max_length=16),
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
